// Shared visual language for the Bi-Rite Operations tool suite
// (matches Coffee Brew Schedule / Ops Bag Packing Tool)

export const theme = {
  pageBg: '#071417',
  headerGradient: 'linear-gradient(90deg, #0d7d6f 0%, #14b8a6 100%)',
  cardBg: '#0c2129',
  cardBgAlt: '#0a1c22',
  cardBorder: '#1f4a4f',
  cardBorderHover: '#2dd4bf',
  textPrimary: '#f2f9f8',
  textSecondary: '#7fa8ac',
  textMuted: '#4d6d70',
  accent: '#2dd4bf',
  accentSoft: 'rgba(45, 212, 191, 0.12)',
  buttonGradient: 'linear-gradient(90deg, #0d9488 0%, #2dd4bf 100%)',
  buttonGradientDisabled: 'linear-gradient(90deg, #1f4a4f 0%, #2a5a5f 100%)',
  danger: '#f87171',
  dangerSoft: 'rgba(248, 113, 113, 0.12)',
  warn: '#fbbf24',
  highlightBg: '#fde047',
  highlightText: '#1a1a1a',
  sectionRowBg: '#12333a',
  editedDot: '#2dd4bf',
  cellHoverBg: 'rgba(45, 212, 191, 0.07)',
  cellEditingBg: 'rgba(45, 212, 191, 0.16)',
  rowHoverBg: 'rgba(255, 255, 255, 0.02)',
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
};

export const s = {
  page: {
    minHeight: '100vh',
    background: theme.pageBg,
    fontFamily: theme.fontFamily,
    color: theme.textPrimary,
  },
  header: {
    background: theme.headerGradient,
    padding: '18px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 16 },
  logoBox: {
    background: '#fff',
    border: '2px solid #111',
    borderRadius: 4,
    padding: '6px 10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    lineHeight: 1,
  },
  logoText: { fontWeight: 900, fontSize: 15, color: '#111', letterSpacing: 0.5 },
  logoSub: { fontSize: 6, color: '#333', letterSpacing: 1, marginTop: 2 },
  toolTitle: { fontSize: 21, fontWeight: 800, color: '#fff', margin: 0 },
  toolSubtitle: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.85)',
    letterSpacing: 1.5,
    fontWeight: 700,
    marginTop: 2,
  },
  headerDate: { color: '#fff', fontSize: 14, fontWeight: 500 },
  headerRight: { display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap', justifyContent: 'flex-end' },
  hubLink: {
    color: '#fff',
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: 8,
    padding: '7px 14px',
    fontSize: 12,
    fontWeight: 600,
    textDecoration: 'none',
    whiteSpace: 'nowrap',
  },
  stepBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: '18px 16px',
    borderBottom: `1px solid ${theme.cardBorder}`,
  },
  content: {
    margin: '0 auto',
    padding: '32px 24px 48px',
  },
  contentNarrow: {
    maxWidth: 700,
  },
  contentWide: {
    maxWidth: 'min(1700px, 96vw)',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 1.5,
    color: theme.accent,
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  card: {
    background: theme.cardBg,
    border: `1px solid ${theme.cardBorder}`,
    borderRadius: 10,
    padding: 24,
  },
  primaryButton: {
    background: theme.buttonGradient,
    color: '#04211d',
    border: 'none',
    borderRadius: 8,
    padding: '14px 28px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
  },
  primaryButtonDisabled: {
    background: theme.buttonGradientDisabled,
    color: '#5c8b8b',
    border: 'none',
    borderRadius: 8,
    padding: '14px 28px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'not-allowed',
  },
  secondaryButton: {
    background: 'transparent',
    color: theme.textSecondary,
    border: `1px solid ${theme.cardBorder}`,
    borderRadius: 8,
    padding: '12px 22px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  footer: {
    textAlign: 'center',
    color: theme.textMuted,
    fontSize: 11,
    letterSpacing: 1,
    padding: '24px 0 40px',
  },
};
